---
title: "**CV**"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)

```

<div class="row" style="padding-top: 30px;  padding-right: 100px; padding-left: 30px; ">

```{r, echo=FALSE,results="asis"}

cv<-read_excel("cv_zmm.xlsx",sheet="CV") %>%
  arrange(desc(End))
categories<-c("Education","Employment","Volunteering","Projects","Conferences",
              "Certifications","Awards","Publications","Media")

for (c in categories){
  cv_sub<-subset(cv,Category==c & CV=="Include")
  
  cat("#"," **", c, "** ", "\n",sep="")
  
  for (i in 1:nrow(cv_sub)){
    entry<-cv_sub[i,]
      
      start<-as.character(paste(entry$Start_Month,"-",entry$Start_Year,sep=""))
        end<-as.character(paste(entry$End_Month,"-",entry$End_Year,sep=""))
        timing<-as.character(paste(start," to ",end,sep=""))
        location<-if(is.na(entry$Loc_Small)==T) {entry$Loc_Large} else {
                    paste(entry$Loc_Small,", ",entry$Loc_Large,sep="")}
        period<-paste(as.character(c(round(entry$Time,digits=0), " ", entry$Time_Unit)))

        org<-if(is.na(entry$Org_Link)==T) {entry$Organization} else {
          paste("[",entry$Organization,"]","(",entry$Org_Link,")",sep="")}  
        
        org.link<-if(is.na(entry$Org_Link)==T) {""} else {
          paste("[","Website","]","(",entry$Org_Link,")",sep="")}
        
        org.acr<-if(is.na(entry$Org_Acr)==T) {entry$Organization} else {
          paste(entry$Organization," (",entry$Org_Acr,")",sep="")}  
      
        title.acr<-if(is.na(entry$Title_Acr)==T) {entry$Title} else {
                  paste(entry$Title," (",entry$Title_Acr,")",sep="")}  
        
        description<-paste(
          "**",title.acr,"**", "\n","\n",
          "- ", entry$Description, "\n","\n",
          ifelse(is.na(entry$Tasks)==T,"",paste("- ",entry$Tasks,"\n","\n")),
          ifelse(is.na(entry$Achievements)==T,"",paste("- ",entry$Achievements,"\n","\n")),
          ifelse(is.na(entry$Lessons)==T,"",paste("- ",entry$Lessons,"\n","\n")),sep="")
          
      
                      
      #Setting up media (if present)  
      M1 <- paste0(
        ifelse(is.na(entry$M1)==T,"",
               paste0("[",entry$M1_Desc,
                      "](https://zacharymilosmoore.ca/media/",
                      entry$M1,entry$M1_Type,")",
                      "\n","\n")))
      
      M2 <- paste0(
        ifelse(is.na(entry$M2)==T,"",
               paste0("[",entry$M2_Desc,
                      "](https://zacharymilosmoore.ca/media/",
                      entry$M2,entry$M2_Type,")",
                      "\n","\n")))
      
      M3 <- paste0(
        ifelse(is.na(entry$M3)==T,"",
               paste0("[",entry$M3_Desc,
                      "](https://zacharymilosmoore.ca/media/",
                      entry$M3,entry$M3_Type,")",
                      "\n","\n")))
      
      
      #Setting up Links (if present)
      
      L1<-paste(
        ifelse(is.na(entry$L1)==T,"",
               paste("[",entry$L1_Desc,"](",entry$L1,")","\n","\n",sep="")),sep="")
      L2<-paste(
        ifelse(is.na(entry$L2)==T,"",
               paste("[",entry$L2_Desc,"](",entry$L2,")","\n","\n",sep="")),sep="")
      L3<-paste(
        ifelse(is.na(entry$L3)==T,"",
               paste("[",entry$L3_Desc,"](",entry$L3,")","\n","\n",sep="")),sep="")
      
    #Printing Entries for Markdown
      
      if (c %in% c("Projects")){
        cat("##", title.acr,"{.tabset}", "\n","\n")+
          cat(timing," (",period,") ",location," ","\n","\n",org,"\n","\n",sep="")
        
        cat("###", "Description", "\n","\n")
        cat(description, "\n","\n")
        
        #Checking for media, add media tab
        if(M1==""){""} else {
          cat("###", "Media", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(M1,M2,M3,"\n","\n")
        }
        
        #Checking for links, add links tab
        if(L1==""){""} else {
          cat("###", "Links", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(L1,L2,L3,"\n","\n")
        }
        
        #Add and activate empty Tab with Title to hide others   
        cat("###", "-","{.active}", "\n","\n")
        cat("**",title.acr,"**", "\n","\n",sep="")
        
      } 
      
      if (c %in% c("Certifications")){
        cat("##", title.acr, "\n","\n")+
          cat(timing," (",period,") ",location," ","\n","\n",org,"\n","\n",sep="")
      } 
      
      if (c %in% c("Media")){ # Just L1
        cat("###", L1, "\n","\n")
      }
      
      if (c %in% c("Awards","Accreditations")){ 
        cat("###", org.acr, "-", title.acr, start, "\n","\n")
      }
      
      if (c %in% c("Publications")){ 
        cat("###", L1, "\n","\n")
      }
      
      if (c %in% c("Conferences")){ # For general tabset entries (Employment, education)
          
        cat("##",org.acr,"{.tabset}", "\n","\n")+
          cat(start," (",period,") ",location," ",org.link,"\n","\n",sep="")
        
        cat("###", "Description", "\n","\n")
        cat(description, "\n","\n")
        
        #Checking for media, add media tab
        if(M1==""){""} else {
          cat("###", "Media", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(M1,M2,M3,"\n","\n")
        }
        
        #Checking for links, add links tab
        if(L1==""){""} else {
          cat("###", "Links", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(L1,L2,L3,"\n","\n")
        }
        
        #Add and activate empty Tab with Title to hide others   
        cat("###", "-","{.active}", "\n","\n")
        cat("**",title.acr,"**", "\n","\n",sep="")
        
      }
      
      if (c %in% c("Employment","Education","Volunteering")){ # For general tabset entries (Employment, education)
          
        cat("##",org.acr,"{.tabset}", "\n","\n")+
          cat(timing," (",period,") ",location," ",org.link,"\n","\n",sep="")
        
        cat("###", "Description", "\n","\n")
        cat(description, "\n","\n")
        
        #Checking for media, add media tab
        if(M1==""){""} else {
          cat("###", "Media", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(M1,M2,M3,"\n","\n")
        }
        
        #Checking for links, add links tab
        if(L1==""){""} else {
          cat("###", "Links", "\n", "\n")
            cat("**",title.acr,"**", "\n","\n",sep="")
            cat(L1,L2,L3,"\n","\n")
        }
        
        #Add and activate empty Tab with Title to hide others   
        cat("###", "-","{.active}", "\n","\n")
        cat("**",title.acr,"**", "\n","\n",sep="")
        
      }
      
    #Add spaces between entries
    cat("\n","<br>","\n","\n")

  }
  cat("\n","<br>","\n","\n")
}

```
</div>
<div class="header">

Last Updated: 
```{r,results="asis",echo=F} 

cat(format(Sys.time(),"%c"))
```
[GitHub Source](https://github.com/zacharymilosmoore/zacharymilosmoore.github.io)

</div>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">
</div>
